
@baseUrl = http://localhost
@prefix = api
@port = 5555


### get all planets
GET {{baseUrl}}:{{port}}/{{prefix}}/planets


### filter planets by population
POST {{baseUrl}}:{{port}}/{{prefix}}/planet?population=30000&size=20
Content-Type: application/json

{
  "colonized": true,
  "population": 123403,
  "size": 20
}


### get homepage
GET {{baseUrl}}:{{port}}/{{prefix}}/


### page not found
POST {{baseUrl}}:{{port}}/{{prefix}}/just-a-random-page