
@baseUrl = http://localhost
@prefix = api
@port = 5555


### get all planets
GET {{baseUrl}}:{{port}}/{{prefix}}/planets


### filter planets by population ( from query params )
POST {{baseUrl}}:{{port}}/{{prefix}}/planet?population=223320&size=20
Content-Type: application/json

{
  "bodyProperty": true
}


### get homepage
GET {{baseUrl}}:{{port}}/{{prefix}}/


### page not found
POST {{baseUrl}}:{{port}}/{{prefix}}/just-a-random-page